"""
Cart router — endpoints for managing the session-based shopping cart.
Called by Rock8 voice agent tool calls.

SESSION DESIGN:
  The cart key is resolved server-side in this priority order:
    1. X-Caller-Number header (injected by Rock8/SIP — most reliable)
    2. caller_number body param (AI passes from call metadata)
    3. session_id body param (last resort fallback)
  This means the AI does NOT need to remember or track any session ID.
  The same caller phone = same cart throughout the entire call.
"""
import re
import math
import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from motor.motor_asyncio import AsyncIOMotorDatabase

from app.database import get_db
from app.schemas.cart_schema import (
    AddToCartRequest,
    CalculateTotalRequest,
    CartResponse,
    CalculateTotalResponse,
    CartItemSchema,
    RemoveFromCartRequest,
    GetItemPriceRequest,
    GetItemPriceResponse,
    VariationPriceInfo,
)
from app.services.menu_service import validate_item, get_item_price_per_gram
from datetime import datetime

logger = logging.getLogger(__name__)
router = APIRouter(tags=["Cart"])


def _normalize_phone(raw: str) -> str:
    """Strip formatting from phone number and return digits+leading+ only."""
    return re.sub(r"[\s\-\(\)]", "", raw.strip())


def _resolve_session(raw_request: Request, caller_number: Optional[str], session_id: str) -> str:
    """
    Resolve the cart session key.
    We now prefer the session_id explicitly generated by the AI as a 6-digit random number.
    If not present, fallback to Rock8 X-Caller-Number header or caller_number.
    """
    session_id = session_id.strip()

    # Priority 1: session_id from AI (6-digit random number)
    if session_id and session_id != "+919876543210":
        logger.info(f"[SESSION] Resolved from session_id param: {session_id}")
        return session_id

    # Priority 2: Rock8 SIP header
    header_phone = raw_request.headers.get("x-caller-number", "").strip()
    if header_phone and not header_phone.startswith("{"):
        digits = _normalize_phone(header_phone)
        if digits and digits.lstrip("+").isdigit():
            logger.info(f"[SESSION] Resolved from SIP header (fallback): {digits}")
            return digits

    # Priority 3: caller_number body param
    if caller_number:
        digits = _normalize_phone(caller_number)
        if digits and digits.lstrip("+").isdigit() and len(digits) >= 7:
            logger.info(f"[SESSION] Resolved from caller_number param (fallback): {digits}")
            return digits

    # Final fallback
    logger.info(f"[SESSION] Using session_id as fallback: {session_id}")
    return session_id


async def _get_or_create_cart(db: AsyncIOMotorDatabase, session_key: str) -> dict:
    """Get existing cart or create new one for the session."""
    cart = await db["carts"].find_one({"session_id": session_key})
    if cart is None:
        cart = {
            "session_id": session_key,
            "items": [],
            "total_amount": 0.0,
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        }
        await db["carts"].insert_one(cart)
    return cart


def _recalculate_total(items: list) -> float:
    """Recalculate total from cart items."""
    return sum(item.get("final_price", 0) for item in items)


def _variation_to_grams(variation: str) -> int:
    """Convert a variation string like '1 Kg', '500 Grms' to grams. Returns 0 if not weight-based."""
    if not variation:
        return 0
    v = variation.strip().lower()
    if "kg" in v:
        try:
            num = float(v.replace("kg", "").strip())
            return int(num * 1000)
        except ValueError:
            return 0
    if "grms" in v or "grams" in v:
        try:
            num = float(v.replace("grms", "").replace("grams", "").strip())
            return int(num)
        except ValueError:
            return 0
    return 0


def _consolidate_cart_items(items: list) -> list:
    """
    Group cart items by item_name, combine variations into total weight.
    Returns a single entry per item with human-readable combined weight.
    e.g., [1Kg qty=2, 500Grms qty=1] -> [2.5 Kg, combined price]
    """
    from collections import OrderedDict
    grouped: OrderedDict = OrderedDict()

    for item in items:
        name = item.get("item_name", "")
        var = item.get("variation", "") or ""
        qty = item.get("quantity", 1)
        grams = _variation_to_grams(var)

        if name not in grouped:
            grouped[name] = {
                "item_name": name,
                "total_grams": 0,
                "total_qty": 0,
                "final_price": 0.0,
                "is_weight_based": False,
                "variation": var,
            }
        g = grouped[name]

        if grams > 0:
            # Weight-based item (meat)
            g["is_weight_based"] = True
            g["total_grams"] += grams * qty
            g["final_price"] += item.get("final_price", 0)
        else:
            # Piece/packet based (masale)
            g["total_qty"] += qty
            g["final_price"] += item.get("final_price", 0)
            g["variation"] = var or "Pcs"

    result = []
    for g in grouped.values():
        if g["is_weight_based"]:
            total_g = g["total_grams"]
            if total_g >= 1000:
                kg = total_g / 1000
                if kg == int(kg):
                    variation_str = f"{int(kg)} Kg"
                else:
                    variation_str = f"{kg} Kg"
            else:
                variation_str = f"{total_g} Grms"
            result.append(CartItemSchema(
                item_name=g["item_name"],
                variation=variation_str,
                quantity=1,
                price=g["final_price"],
                final_price=g["final_price"],
            ))
        else:
            result.append(CartItemSchema(
                item_name=g["item_name"],
                variation=g["variation"],
                quantity=g["total_qty"],
                price=round(g["final_price"] / max(g["total_qty"], 1), 2),
                final_price=g["final_price"],
            ))
    return result


@router.post("/add_to_cart", response_model=CartResponse)
async def add_to_cart(
    request: AddToCartRequest,
    raw_request: Request,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Add an item to the cart.
    Supports two modes:
      - Standard: pass variation + quantity (exact menu variation name).
      - Custom weight: pass custom_weight_kg (e.g. 4.2) — price is calculated
        proportionally from the item's per-gram rate. No variation/quantity needed.
    """
    session_key = _resolve_session(raw_request, request.caller_number, request.session_id)

    print(f"\n==============================================")
    print(f"📞 Riya CALLED: ADD TO CART")
    print(f"📞 SESSION KEY: {session_key}")
    print(f"📞 ITEM: {request.item_name} | VARIATION: {request.variation} | QTY: {request.quantity} | CUSTOM_KG: {request.custom_weight_kg}")
    print(f"==============================================\n")

    logger.info(
        f"[CART] add_to_cart: key={session_key}, item={request.item_name}, "
        f"var={request.variation}, qty={request.quantity}, custom_kg={request.custom_weight_kg}"
    )

    # ── CUSTOM WEIGHT MODE ────────────────────────────────────────────────────
    if request.custom_weight_kg is not None:
        try:
            price_info = await get_item_price_per_gram(request.item_name)
        except ValueError as e:
            logger.warning(f"Custom weight price lookup failed: {e}")
            return CartResponse(success=False, message=str(e), cart_items=[], cart_total=0.0)
        except Exception as e:
            logger.error(f"Menu service error during custom weight lookup: {e}")
            raise HTTPException(status_code=503, detail="Menu service unavailable")

        price_per_gram: float = price_info["price_per_gram"]
        resolved_name: str = price_info.get("item_name", request.item_name)
        weight_kg: float = request.custom_weight_kg
        weight_grams: float = weight_kg * 1000

        # Exact price rounded to 2 decimal places
        exact_price = round(price_per_gram * weight_grams, 2)

        # Human-readable variation label (e.g. "4.2 Kg", "500 Grms")
        if weight_kg >= 1:
            kg_str = f"{weight_kg:.3f}".rstrip("0").rstrip(".")
            variation_label = f"{kg_str} Kg"
        else:
            grams_int = int(round(weight_grams))
            variation_label = f"{grams_int} Grms"

        cart = await _get_or_create_cart(db, session_key)
        current_items = list(cart.get("items", []))

        # Check for duplicate custom-weight entry for same item
        found = False
        for existing_item in current_items:
            if (
                existing_item.get("item_name", "").lower() == resolved_name.lower()
                and existing_item.get("variation") == variation_label
            ):
                # Accumulate: double the weight and double the price
                existing_item["quantity"] += 1
                existing_item["final_price"] = round(existing_item["price"] * existing_item["quantity"], 2)
                found = True
                break

        if not found:
            new_item = {
                "item_name": resolved_name,
                "variation": variation_label,
                "quantity": 1,
                "price": exact_price,
                "final_price": exact_price,
                "is_custom_weight": True,
            }
            current_items.append(new_item)
            logger.info(f"[CART CUSTOM] Added '{resolved_name}' @ {variation_label} for ₹{exact_price}")

        cart["items"] = current_items
        cart["total_amount"] = _recalculate_total(current_items)
        cart["updated_at"] = datetime.utcnow()

        await db["carts"].update_one(
            {"session_id": session_key},
            {"$set": {"items": cart["items"], "total_amount": cart["total_amount"], "updated_at": cart["updated_at"]}}
        )

        consolidated = _consolidate_cart_items(current_items)
        return CartResponse(
            success=True,
            message=f"'{resolved_name}' ({variation_label}) added to cart — ₹{exact_price}",
            cart_items=consolidated,
            cart_total=cart["total_amount"],
        )

    # ── STANDARD VARIATION MODE ───────────────────────────────────────────────
    try:
        item_info = await validate_item(request.item_name, request.variation)
    except ValueError as e:
        # ── FALLBACK ──
        # If LLM passed "700 Grms" as variation but it's not in menu,
        # extract the weight and retry as custom weight mode automatically.
        grams = _variation_to_grams(request.variation)
        if grams > 0:
            logger.info(f"Fallback: variation '{request.variation}' not found, retrying as custom weight {grams}g")
            request.custom_weight_kg = grams / 1000.0
            request.variation = None
            return await add_to_cart(request, raw_request, db)
            
        logger.warning(f"Menu validation failed: {e}")
        return CartResponse(success=False, message=str(e), cart_items=[], cart_total=0.0)
    except Exception as e:
        logger.error(f"Menu service error: {e}")
        raise HTTPException(status_code=503, detail="Menu service unavailable")

    cart = await _get_or_create_cart(db, session_key)
    current_items = list(cart.get("items", []))

    # Check for duplicate item+variation — increment quantity if found
    found = False
    for existing_item in current_items:
        if (
            existing_item.get("item_name", "").lower() == item_info["item_name"].lower()
            and existing_item.get("variation") == item_info["variation"]
        ):
            existing_item["quantity"] += request.quantity
            existing_item["final_price"] = existing_item["quantity"] * existing_item["price"]
            found = True
            logger.info(f"Incremented '{item_info['item_name']}' to qty={existing_item['quantity']}")
            break

    if not found:
        new_item = {
            "item_name": item_info["item_name"],
            "variation": item_info["variation"],
            "quantity": request.quantity,
            "price": item_info["price"],
            "final_price": item_info["price"] * request.quantity,
        }
        current_items.append(new_item)
        logger.info(f"Added new item '{item_info['item_name']}' to cart")

    cart["items"] = current_items
    cart["total_amount"] = _recalculate_total(current_items)
    cart["updated_at"] = datetime.utcnow()
    
    await db["carts"].update_one(
        {"session_id": session_key},
        {"$set": {"items": cart["items"], "total_amount": cart["total_amount"], "updated_at": cart["updated_at"]}}
    )

    consolidated = _consolidate_cart_items(current_items)
    return CartResponse(
        success=True,
        message=f"'{item_info['item_name']}' added to cart successfully",
        cart_items=consolidated,
        cart_total=cart["total_amount"],
    )



@router.post("/calculate_total", response_model=CalculateTotalResponse)
async def calculate_total(
    request: CalculateTotalRequest,
    raw_request: Request,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Return full cart contents and total amount."""
    session_key = _resolve_session(raw_request, request.caller_number, request.session_id)

    print(f"\n==============================================")
    print(f"📞 Riya CALLED: CALCULATE TOTAL")
    print(f"📞 SESSION KEY: {session_key}")
    print(f"==============================================\n")

    logger.info(f"[CART] calculate_total: key={session_key}")

    cart = await db["carts"].find_one({"session_id": session_key})

    if cart is None or not cart.get("items"):
        return CalculateTotalResponse(
            success=True,
            message="Cart is empty",
            cart_items=[],
            total_amount=0.0,
            item_count=0,
        )

    consolidated = _consolidate_cart_items(cart["items"])
    return CalculateTotalResponse(
        success=True,
        message="Cart total calculated",
        cart_items=consolidated,
        total_amount=cart.get("total_amount", 0.0),
        item_count=len(consolidated),
    )


@router.post("/remove_from_cart", response_model=CartResponse)
async def remove_from_cart(
    request: RemoveFromCartRequest,
    raw_request: Request,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Remove an item (fully or partially) from the cart."""
    session_key = _resolve_session(raw_request, request.caller_number, request.session_id)

    print(f"\n==============================================")
    print(f"📞 Riya CALLED: REMOVE FROM CART")
    print(f"📞 SESSION KEY: {session_key}")
    print(f"📞 ITEM: {request.item_name} | QTY TO REMOVE: {request.quantity}")
    print(f"==============================================\n")

    logger.info(f"[CART] remove_from_cart: key={session_key}, item={request.item_name}, qty={request.quantity}")

    cart = await db["carts"].find_one({"session_id": session_key})

    if cart is None or not cart.get("items"):
        return CartResponse(
            success=False,
            message="Cart is empty, nothing to remove",
            cart_items=[],
            cart_total=0.0,
        )

    current_items = list(cart["items"])

    # Find all entries for this item
    matching_indices = [
        i for i, item in enumerate(current_items)
        if item.get("item_name", "").lower() == request.item_name.lower()
    ]

    if not matching_indices:
        return CartResponse(
            success=False,
            message=f"Item '{request.item_name}' not found in cart",
            cart_items=_consolidate_cart_items(current_items),
            cart_total=cart.get("total_amount", 0.0),
        )

    # If no quantity specified → remove ALL entries of this item
    if not request.quantity:
        current_items = [item for i, item in enumerate(current_items) if i not in matching_indices]
        msg = f"'{request.item_name}' completely removed from cart"
    else:
        # Partial removal — remove the specified weight
        grams_to_remove = _variation_to_grams(request.quantity)

        if grams_to_remove <= 0:
            # Non-weight quantity (e.g., packet count for masale)
            try:
                qty_to_remove = int(re.sub(r'[^0-9]', '', request.quantity) or '1')
            except ValueError:
                qty_to_remove = 1
            for idx in matching_indices:
                item = current_items[idx]
                if item["quantity"] > qty_to_remove:
                    item["quantity"] -= qty_to_remove
                    item["final_price"] = item["quantity"] * item["price"]
                    break
                else:
                    current_items[idx] = None  # Mark for removal
                    break
            current_items = [i for i in current_items if i is not None]
            msg = f"{request.quantity} of '{request.item_name}' removed from cart"
        else:
            # Weight-based partial removal
            remaining_to_remove = grams_to_remove
            # Process entries from smallest variation to largest (remove small packs first)
            sorted_indices = sorted(
                matching_indices,
                key=lambda idx: _variation_to_grams(current_items[idx].get("variation", ""))
            )

            for idx in sorted_indices:
                if remaining_to_remove <= 0:
                    break
                item = current_items[idx]
                item_grams = _variation_to_grams(item.get("variation", ""))
                if item_grams <= 0:
                    continue
                total_item_grams = item_grams * item["quantity"]

                if total_item_grams <= remaining_to_remove:
                    # Remove this entire entry
                    remaining_to_remove -= total_item_grams
                    current_items[idx] = None  # Mark for removal
                else:
                    # Reduce quantity
                    units_to_remove = remaining_to_remove // item_grams
                    if units_to_remove > 0:
                        item["quantity"] -= units_to_remove
                        item["final_price"] = item["quantity"] * item["price"]
                        remaining_to_remove -= units_to_remove * item_grams
                    remaining_to_remove = 0

            current_items = [i for i in current_items if i is not None]
            msg = f"{request.quantity} of '{request.item_name}' removed from cart"

    cart["items"] = current_items
    cart["total_amount"] = _recalculate_total(current_items)
    cart["updated_at"] = datetime.utcnow()

    await db["carts"].update_one(
        {"session_id": session_key},
        {"$set": {"items": cart["items"], "total_amount": cart["total_amount"], "updated_at": cart["updated_at"]}}
    )

    consolidated = _consolidate_cart_items(current_items)
    return CartResponse(
        success=True,
        message=msg,
        cart_items=consolidated,
        cart_total=cart["total_amount"],
    )


@router.post("/get_item_price", response_model=GetItemPriceResponse)
async def get_item_price(request: GetItemPriceRequest):
    """
    Returns pricing for a weight-based menu item.

    Use cases:
    - Custom weight: Pass custom_weight_kg to get computed_total_price (server-side math).
      Then call add_to_cart with custom_weight_kg.
    - Budget-based: Pass budget (rupees) to get max_weight_kg and actual_cost.
      The response also contains custom_weight_kg_to_add — pass it directly to add_to_cart.
    - Price inquiry: Pass only item_name to get price_per_kg.
    """
    print(f"\n==============================================")
    print(f"📞 Riya CALLED: GET ITEM PRICE")
    print(f"📞 ITEM: {request.item_name} | BUDGET: {request.budget} | CUSTOM_KG: {request.custom_weight_kg}")
    print(f"==============================================\n")

    try:
        price_info = await get_item_price_per_gram(request.item_name)
    except ValueError as e:
        logger.warning(f"[PRICE] {e}")
        return GetItemPriceResponse(
            success=False,
            item_name=request.item_name,
            message=str(e),
        )
    except Exception as e:
        logger.error(f"[PRICE] Unexpected error: {e}")
        raise HTTPException(status_code=503, detail="Menu service unavailable")

    # Use resolved item name from partial matching
    resolved_name: str = price_info.get("item_name", request.item_name)
    price_per_gram: float = price_info["price_per_gram"]
    price_per_kg: float = price_info["price_per_kg"]

    # Build variation list for the response
    variations_out = [
        VariationPriceInfo(
            name=v["name"],
            price=v["price"],
            grams=v["grams"],
            price_per_gram=round(v["price_per_gram"], 6),
        )
        for v in price_info["variations"]
    ]

    # ── Custom weight calculation (SERVER-SIDE MATH) ────────────────────────────
    if request.custom_weight_kg is not None:
        weight_kg = request.custom_weight_kg
        computed_total = round(weight_kg * price_per_kg, 2)

        # Human-readable weight string
        weight_grams = weight_kg * 1000
        if weight_kg >= 1:
            kg_str = f"{weight_kg:.3f}".rstrip("0").rstrip(".")
            weight_human = f"{kg_str} Kg"
        else:
            grams_int = int(round(weight_grams))
            weight_human = f"{grams_int} Grms"

        logger.info(
            f"[PRICE CUSTOM] '{resolved_name}' {weight_kg}kg × ₹{price_per_kg}/kg = ₹{computed_total}"
        )

        return GetItemPriceResponse(
            success=True,
            item_name=resolved_name,
            price_per_gram=round(price_per_gram, 6),
            price_per_kg=round(price_per_kg, 2),
            variations=variations_out,
            custom_weight_kg=weight_kg,
            computed_total_price=computed_total,
            custom_weight_kg_to_add=weight_kg,
            message=(
                f"{weight_human} {resolved_name} — ₹{computed_total:.0f}."
            ),
        )

    # ── Budget calculation ──────────────────────────────────────────────────────
    if request.budget is not None:
        budget = request.budget
        max_grams = int(budget / price_per_gram)  # floor via int()
        if max_grams <= 0:
            min_variation = min(price_info["variations"], key=lambda v: v["grams"])
            return GetItemPriceResponse(
                success=False,
                item_name=resolved_name,
                price_per_gram=round(price_per_gram, 6),
                price_per_kg=round(price_per_kg, 2),
                variations=variations_out,
                budget=budget,
                message=(
                    f"Budget ₹{budget:.0f} is too small. "
                    f"Minimum is {min_variation['name']} at ₹{min_variation['price']:.0f}."
                ),
            )

        actual_cost = round(price_per_gram * max_grams, 2)
        max_weight_kg = max_grams / 1000.0

        if max_grams >= 1000:
            kg_val = max_grams / 1000.0
            kg_str = f"{kg_val:.3f}".rstrip("0").rstrip(".")
            human = f"{kg_str} Kg"
        else:
            human = f"{max_grams} Grms"

        logger.info(
            f"[PRICE BUDGET] '{resolved_name}' budget=₹{budget} "
            f"→ {max_grams}g = {human} @ ₹{actual_cost}"
        )

        return GetItemPriceResponse(
            success=True,
            item_name=resolved_name,
            price_per_gram=round(price_per_gram, 6),
            price_per_kg=round(price_per_kg, 2),
            variations=variations_out,
            budget=budget,
            max_weight_grams=max_grams,
            max_weight_kg=round(max_weight_kg, 4),
            max_weight_human=human,
            actual_cost=actual_cost,
            custom_weight_kg_to_add=round(max_weight_kg, 4),
            message=(
                f"₹{budget:.0f} mein {human} milega — actual cost ₹{actual_cost:.2f}."
            ),
        )

    # ── Price info only (no budget, no custom weight) ───────────────────────────
    return GetItemPriceResponse(
        success=True,
        item_name=resolved_name,
        price_per_gram=round(price_per_gram, 6),
        price_per_kg=round(price_per_kg, 2),
        variations=variations_out,
        message=(
            f"Price per gram: ₹{price_per_gram:.4f}. "
            f"Price per kg: ₹{price_per_kg:.2f}."
        ),
    )

